# Generated by Django 5.0.6 on 2024-12-30 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skills', models.TextField(blank=True, default='Not Updated', max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Application_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Role', models.CharField(max_length=100)),
                ('Pay', models.IntegerField()),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Job_Description', models.TextField()),
                ('Reporting_Address', models.TextField()),
                ('Application_Exp_Date', models.DateField()),
                ('Posted_Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_Name', models.CharField(default='Not Updated', max_length=250)),
            ],
        ),
    ]
