# Generated by Django 5.0.6 on 2024-12-30 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobPosts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='Applicant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Applied_app_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='JobApplication', to='JobPosts.applicantprofile'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='JobApplication', to='JobPosts.jobposts'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='Manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposts',
            name='Manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Job_Posts', to='JobPosts.managerprofile'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JobPosts.managerprofile'),
        ),
    ]
